---
- hosts: Servers
  remote_user: melhossiny
  become: yes
  tasks: 
  - name: Get Service Status
    systemd:
      name: "firewalld"
    register: firewalld

  - debug:
      msg: "Firwall is working fine."
    when: firewalld.status.ActiveState == "active"

  - debug:
      msg: "Firwall Not Working!!.."
    when: firewalld.status.ActiveState != "active"

  - name: Starte Firewalld Servicse
    service:
      name: firewalld
      state: started
      enabled: yes
    when: firewalld.status.ActiveState != "active"        