---
- hosts: Servers
  remote_user: melhossiny
  become: yes
  
  vars:
    - passwrd: asd.123
  
  tasks: 
    
    - name: Delete Admin User
      user:
        name: Admin
        state: absent
        remove: yes

    - name: Recreate User Admin with New Password
      user:  
        name: Admin
        uid: 1050
        group: root
        password: "{{ passwrd | password_hash('sha512') }}"