---
- hosts: Servers
  remote_user: melhossiny
  become: yes
  tasks:
    - name: Create file
      file:
        path: /root/MyNewFILE
        state: touch
        owner: melhossiny
        group: IT
        mode: '1777'
