---
- hosts: Servers
  remote_user: melhossiny
  become: yes
  tasks: 
   - name: Check if file exists using file module
     file:
       path: /root/MyFile
       state: file
     register: FileCheck

   - name: Print file status
     debug:
       var: FileCheck.stat.exists

   - name: Execute task only if file exists
     stat:
      path: /root/MyFile
    register: FileCheck
    when: FileCheck.stat.exists

  - name: Execute task only if file does not exist
    stat:
     path: /root/MyFile
    register: FileCheck
    when: not FileCheck.stat.exists     
